# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-20 15:26
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_auto_20170620_1904'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2017, 6, 20, 15, 26, 24, 752803, tzinfo=utc)),
        ),
    ]
