# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-19 09:55
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_auto_20170620_2126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2017, 7, 19, 9, 55, 24, 109537, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='news',
            name='photo',
            field=models.FileField(blank='true', upload_to='media/'),
        ),
    ]
