# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-19 10:34
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_auto_20170719_1555'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='hight_field',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='news',
            name='width_field',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='news',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2017, 7, 19, 10, 34, 54, 507116, tzinfo=utc)),
        ),
    ]
