# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-20 13:58
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0008_auto_20170720_0040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2017, 7, 20, 13, 58, 57, 937530, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='news',
            name='photo',
            field=models.FileField(null='true', upload_to='media/'),
        ),
    ]
